version: '1'

services:
  mundo-rds:
    image: redis
    container_name: mundo-rds-ctn
    ports:
      - "6379:6379"
  mundo-mysql:
    image: bitnami/mysql:latest
    container_name: mundo-mysql-ctn
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mundo
      - MYSQL_CHARSET=utf8mb4
  mundo-mq:
    image: bitnami/rabbitmq:3.11.18-debian-11-r0
    container_name: mundo-mq-ctn
    ports:
      - "15672:15672"
      - "5672:5672"
      - "25672:25672"
      - "4369:4369"
    environment:
      - RABBITMQ_USERNAME=root
      - RABBITMQ_PASSWORD=123456
      - RABBITMQ_VHOST=/
      - RABBITMQ_PLUGINS=rabbitmq_management,rabbitmq_peer_discovery_k8s,rabbitmq_auth_backend_ldap, rabbitmq_delayed_message_exchange
      - RABBITMQ_COMMUNITY_PLUGINS=https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/3.11.1/rabbitmq_delayed_message_exchange-3.11.1.ez
  mundo-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: mundo-es-ctn
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=pinnacle
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    command: /bin/sh -c "./bin/elasticsearch-plugin list | grep -q analysis-ik || ./bin/elasticsearch-plugin install --batch https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.7.0/elasticsearch-analysis-ik-8.7.0.zip; /usr/local/bin/docker-entrypoint.sh"

